In [1]:
import numpy as np
import keras
import tensorflow as tf

2022-05-09 23:36:05.901139: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-09 23:36:05.901169: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
# datasets = keras.preprocessing.image_dataset.image_dataset_from_directory(
# './../../ML-examples-projects/emojis/', batch_size=64 )

In [3]:
training_data = np.array([["This is the 1st sample."], ["And here's the 2nd sample."]])

vectorizer = tf.keras.layers.TextVectorization(output_mode='int')
vectorizer.adapt(training_data)
vectorizer.get_vocabulary()

2022-05-09 23:37:53.122580: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-09 23:37:53.199392: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-09 23:37:53.199448: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (liberio-X550JX): /proc/driver/nvidia/version does not exist
2022-05-09 23:37:53.299965: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


['', '[UNK]', 'the', 'sample', 'this', 'is', 'heres', 'and', '2nd', '1st']

# Preprocessing (dummy data)
##  turning strings into sequences of integer word indices

In [4]:
integer_data = vectorizer(training_data)
integer_data

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[4, 5, 2, 9, 3],
       [7, 6, 2, 8, 3]])>

## turning strings into sequences of one-hot encoded bigrams

In [5]:
vectorizer = tf.keras.layers.TextVectorization(output_mode='binary', ngrams=2)
vectorizer.adapt(training_data)
vectorizer.get_vocabulary()

['[UNK]',
 'the',
 'sample',
 'this is',
 'this',
 'the 2nd',
 'the 1st',
 'is the',
 'is',
 'heres the',
 'heres',
 'and heres',
 'and',
 '2nd sample',
 '2nd',
 '1st sample',
 '1st']

In [6]:
integer_data = vectorizer(training_data)
integer_data

<tf.Tensor: shape=(2, 17), dtype=float32, numpy=
array([[0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
        1.],
       [0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
        0.]], dtype=float32)>

# Normalizing feautures

In [7]:
training_data = np.random.randint(low=0, high=256,
                                 size=(64, 200, 200, 3)).astype('float32')
training_data[0] # 64 samples , 200x200 wh, 3 colors

array([[[204.,  14.,  78.],
        [211., 218., 105.],
        [227.,  88., 253.],
        ...,
        [ 44.,  69.,  84.],
        [ 52., 145.,   8.],
        [190., 213., 179.]],

       [[139.,  94.,   5.],
        [ 55.,  87., 220.],
        [220., 172., 162.],
        ...,
        [234., 249.,   3.],
        [106., 119., 224.],
        [143., 212., 146.]],

       [[ 51., 112., 183.],
        [ 64., 127., 158.],
        [103., 149., 154.],
        ...,
        [  6.,  31., 126.],
        [149., 164., 123.],
        [232.,  12., 198.]],

       ...,

       [[112.,  11.,  44.],
        [151., 130., 134.],
        [226., 225., 159.],
        ...,
        [128., 234., 169.],
        [ 46., 106., 253.],
        [ 63.,  27.,  80.]],

       [[123., 142., 224.],
        [254.,   1.,  11.],
        [ 57., 221.,  56.],
        ...,
        [  0.,  32., 225.],
        [ 60.,  10., 215.],
        [ 61., 183.,  58.]],

       [[253., 246., 204.],
        [ 24.,  39., 201.],
        [110., 1

In [8]:
normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(training_data)
normalizer

2022-05-09 23:38:13.619810: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 30720000 exceeds 10% of free system memory.
2022-05-09 23:38:14.318917: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 15360000 exceeds 10% of free system memory.
2022-05-09 23:38:14.318983: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 15360000 exceeds 10% of free system memory.


In [9]:
normalizer.get_weights()

[array([127.51912, 127.44459, 127.55171], dtype=float32),
 array([5455.798, 5460.066, 5457.718], dtype=float32),
 2560000]

In [10]:
normalized_data = normalizer(training_data)
normalized_data[0,0,:4]

2022-05-09 23:38:14.895529: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 30720000 exceeds 10% of free system memory.
2022-05-09 23:38:14.914842: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 30720000 exceeds 10% of free system memory.


<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.0354371 , -1.5352703 , -0.67073834],
       [ 1.1302067 ,  1.2255061 , -0.30526286],
       [ 1.3468229 , -0.53381217,  1.6980842 ],
       [ 0.71051294,  0.72477704,  0.70994675]], dtype=float32)>

In [11]:
print('variant : %.2f' % np.var(normalized_data))
print('mean : %.2f' % np.mean(normalized_data))

variant : 1.00
mean : 0.00


In [12]:
training_data.shape

(64, 200, 200, 3)

In [13]:
cropper = tf.keras.layers.CenterCrop(height=150, width=150)
scaler = tf.keras.layers.Rescaling(scale=1/255)

output_data = scaler(cropper(training_data)) # no need .adapt 
# it's stateless ?
# output_data

In [14]:
print(output_data.shape)

(64, 150, 150, 3)


In [15]:
print(np.min(output_data))

0.0


In [16]:
print(np.max(output_data))

1.0


# Building Model

In [17]:
dense = keras.layers.Dense(units=16) # 16 features

In [18]:
inputs = keras.Input(shape=(None, None, 3)) # recieve any width, height, but must have 3 hues

In [19]:
from tensorflow.keras import layers
x = layers.CenterCrop(height=150, width=150)(inputs) # crop any size squeeze to 150x150
x = layers.Rescaling(scale=1/255)(x) # divide inner value by 255

# apply conv & pool layers
x = layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu')(x)
x = layers.MaxPooling2D(pool_size=(3,3))(x)
x = layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu')(x)
x = layers.MaxPooling2D(pool_size=(3,3))(x)
x = layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu')(x)

x = layers.GlobalAveragePooling2D()(x)


num_classes = 10
outputs = layers.Dense(num_classes, activation='softmax')(x)


In [20]:
model = keras.Model(inputs=inputs, outputs=outputs)

# ???

In [21]:
data = np.random.randint(low=0, high=256,
                                 size=(64, 200, 200, 3)).astype('float32')

In [22]:
processed_data = model(data)
print(processed_data.shape) # 10 = num_classes

(64, 10)


In [23]:
processed_data[0]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.10556075, 0.07037984, 0.11208958, 0.07619462, 0.09119809,
       0.11951683, 0.12926115, 0.11057027, 0.08748099, 0.09774783],
      dtype=float32)>

In [24]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None, None, 3)]   0         
                                                                 
 center_crop_1 (CenterCrop)  (None, 150, 150, 3)       0         
                                                                 
 rescaling_1 (Rescaling)     (None, 150, 150, 3)       0         
                                                                 
 conv2d (Conv2D)             (None, 148, 148, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 49, 49, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 47, 47, 32)        9248      
                                                             

# Train model

In [25]:
model.compile(optimizer=keras.optimizers.rmsprop_v2.RMSprop(learning_rate=1e-3),
             loss=keras.losses.CategoricalCrossentropy())


In [26]:
# model.fit()

# Mnist exmaple

In [27]:
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()

In [28]:
X_train.shape

(60000, 28, 28)

In [29]:
# Build simple model
inputs = keras.Input(shape=(28,28))
x = layers.Rescaling(scale=1/255)(inputs)
x = layers.Flatten()(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dense(128, activation='relu')(x)
outputs = layers.Dense(10, activation='softmax')(x)
model = keras.Model(inputs, outputs)
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 28, 28)]          0         
                                                                 
 rescaling_2 (Rescaling)     (None, 28, 28)            0         
                                                                 
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 128)               100480    
                                                                 
 dense_3 (Dense)             (None, 128)               16512     
                                                                 
 dense_4 (Dense)             (None, 10)                1290      
                                                                 
Total params: 118,282
Trainable params: 118,282
Non-trainab

In [30]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')


In [31]:
# train model from numpy data
history = model.fit(X_train, y_train, batch_size=64, epochs=1)

938/938 [==============================] - 3s 2ms/step - loss: 0.2662


In [32]:
# Train model from dataset
dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train)).batch(64)
history = model.fit(dataset, epochs=1)

938/938 [==============================] - 2s 3ms/step - loss: 0.1156


In [33]:
print(history.history)

{'loss': [0.11559464037418365]}


In [34]:
history.epoch

[0]

In [35]:
history.model

In [36]:
history.params

{'verbose': 1, 'epochs': 1, 'steps': 938}

In [37]:
history.validation_data

# Perfomance metrix

In [38]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=[keras.metrics.SparseCategoricalAccuracy(name='acc')]
)

In [39]:
history = model.fit(dataset, epochs=1)

938/938 [==============================] - 3s 3ms/step - loss: 0.0811 - acc: 0.9754


# Pass validation data 

In [40]:
val_dataset = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(64)
history = model.fit(dataset, epochs=1, validation_data=val_dataset)


938/938 [==============================] - 3s 3ms/step - loss: 0.0548 - acc: 0.9833 - val_loss: 0.1122 - val_acc: 0.9667


In [41]:
print(history.validation_data)

None


# Callback to save checkpoints 
### preventing from machine crashing during training session

In [42]:
callbacks = [
    keras.callbacks.ModelCheckpoint(
    filepath='./formal introduction/model_{epoch}',
    save_freq='epoch') # save every epoch 
]


In [43]:
model.fit(dataset, epochs=3, callbacks=callbacks) # chunk checkpoints of training 

Epoch 1/3
935/938 [============================>.] - ETA: 0s - loss: 0.0397 - acc: 0.9882

2022-05-09 23:38:53.938023: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


INFO:tensorflow:Assets written to: ./formal introduction/model_1/assets
938/938 [==============================] - 4s 4ms/step - loss: 0.0399 - acc: 0.9883
Epoch 2/3
938/938 [==============================] - 3s 3ms/step - loss: 0.0313 - acc: 0.9906
Epoch 3/3
938/938 [==============================] - 3s 3ms/step - loss: 0.0241 - acc: 0.9924


# Monitor training progress (TensorBoard)

In [44]:
callbacks = [
    keras.callbacks.TensorBoard(log_dir='./formal introduction/logs/')
]

In [45]:
model.fit(dataset, epochs=2, callbacks=callbacks)

Epoch 1/2
938/938 [==============================] - 3s 3ms/step - loss: 0.0203 - acc: 0.9934
Epoch 2/2
938/938 [==============================] - 2s 3ms/step - loss: 0.0205 - acc: 0.9929


In [46]:
# go to that log dir, then open it in webbrowser

In [53]:
%tensorboard --logdirs logs

UsageError: Line magic function `%tensorboard` not found.


# Custom step training

In [73]:
class CustomModel(keras.Model):
    def train_step(self, data):
        # unpack if it's numpy data
        x, y = data
        with tf.GradientTape() as tape:
            y_pred = self(x, training=True)
            
            loss = self.compiled_loss(y, y_pred,
                                     regularization_losses=self.losses)
            trainable_vars = self.trainable_variables
            gradients = tape.gradient(loss, trainable_vars)
            
            self.optimizer.apply_gradients(zip(gradients, trainable_vars))
            # matrice that tracks the losses
            self.compiled_metrics.update_state(y, y_pred)
            
            return {m.name: m.result() for m in self.metrics}
        

In [79]:
inputs = keras.Input(shape=(28))
outputs = keras.layers.Dense(1)(inputs)
model = CustomModel(inputs, outputs)
model.compile(optimizer='adam', loss='mse', run_eagerly=True,)


In [80]:
model.fit(dataset, epochs=3, )

Epoch 1/3
938/938 [==============================] - 14s 15ms/step - loss: 1250.4594
Epoch 2/3
938/938 [==============================] - 11s 12ms/step - loss: 75.2196
Epoch 3/3
938/938 [==============================] - 11s 12ms/step - loss: 23.0710


# Hyperparameters Tunning make perfect model

In [94]:
def build_model(hp):
    inputs = keras.Input(shape=(28,))
    x = layers.Dense(
        units=hp.Int('units', min_value=32, max_value=512, step=32),
        activation='relu')(inputs)
    outputs = layers.Dense(10, activation='softmax')(x)
    model = keras.Model(inputs, outputs)
    model.compile(
        optimizer=keras.optimizers.adam_v2.Adam(
            hp.Choice('learning_rate',
                      values=[1e-2, 1e-3, 1e-4])),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy'])
    return model

In [95]:
import keras_tuner

tuner = keras_tuner.tuners.Hyperband(
  build_model,
  objective='val_loss',
  max_epochs=100,
  executions_per_trial=2,
  directory='./my_dir')

INFO:tensorflow:Reloading Oracle from existing project my_dir/untitled_project/oracle.json


In [97]:
# .search == .fit but tuner
# tuner.search(dataset, validation_data=val_dataset)

In [98]:
# models = tuner.get_best_models(num_models=2)